### ISSUE TITLE
运行错误：找不到self._cookies['_xsrf']

### ISSUE THREAD

**Issue by cryptowen** [leodas/ZhihuHelper#3]
我运行时报错信息如下：

```
Traceback (most recent call last):
  File "answer.py", line 21, in <module>
    if not session.login(options.username, options.passwd):
  File "D:\cygwin\home\yely\project\ZhihuHelper\session.py", line 41, in login
    res = self.postData(url=zhihu.LOGIN_URL, data=login_data)
  File "D:\cygwin\home\yely\project\ZhihuHelper\session.py", line 30, in postDat
a
    data['_xsrf'] = self._cookies['_xsrf']
  File "C:\Python27\lib\site-packages\requests\cookies.py", line 248, in __getit
em__
    return self._find_no_duplicates(name)
  File "C:\Python27\lib\site-packages\requests\cookies.py", line 298, in _find_n
o_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='_xsrf', domain=None, path=None"
```

进入pdb调试时，第一次是有cookies信息，也有_xsrf字段，但是使用self._cookies['_xsrf']方法获取时还是报错，清除cookies信息重新登陆后再调试cookies显示是空。

```
ipdb> pp self._cookies
<<class 'requests.cookies.RequestsCookieJar'>[]>
```

想请问一下

```
data['_xsrf'] = self._cookies['_xsrf']
```

这句代码的用意以及为什么会出现这种错误。

**Comment by meganjjzhang** [comment]
我还没有学过Python哦

2014-03-21 1:05 GMT+08:00 Wenchao Hu notifications@github.com:

**Comment by leodas** [comment]
你好，_xsrf字段是tornado服务器应对cookies伪造的一个安全手段。在部分提交数据中需要使用这个字段。可能由于知乎的更新，似乎不能很好地工作。这段代码只是一个试验品，你可以尝试查看最新的知乎页面结构以修复这个问题:)

**Comment by lyanlei** [comment]
你是怎么解决的，遇到同样的错误
